version: 2

models:
  - name: customers
    description: one record per customer with fields from orders
    columns:
     - name: customer_id
       description: primary key of the model
       tests:
         - unique
         - not_null
     - name: first_order_date
       description: NULL if customer has not yet placed an order


  - name: stg_customers
    description: cleans up customer data
    columns:
      - name: customer_id
        description: primary key
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: cleans up order data
    columns:
      - name: order_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id